spring:
  application:
    name: player-service
  config:
    import: "optional:configserver:http://localhost:8088"




#spring.application.name=player-service
#
#server.port=0
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.show-sql=true
#spring.datasource.url=jdbc:postgresql://localhost:5432/player
#spring.datasource.username=postgres
#spring.datasource.password=root
