spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/api/v1/player/**
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/v1/team/**
      discovery:
        locator:
          enabled: true
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info

